name: bideafactory-main

services:
  bookingapi:
    build: bookingapi
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/db_booking
      DB_USER_NAME: postgres
      DB_PASSWORD: mypassword
    restart: always
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: db_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5 
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
